# @reference:
#   https://docs.docker.com/install/linux/docker-ce/ubuntu/
#   https://docs.docker.com/compose/install/
#   https://docs.docker.com/compose/compose-file/
#   https://hub.docker.com/r/phpmyadmin/phpmyadmin
# 
#   chmod 755 ./conf
#   chmod 644 ./conf/mysqld.cnf
#
version: "3"
services:
  mysql:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: mysql
    hostname: mysql
    image: icmdb/mysql:latest
    environment:
      - MYSQL_IMAGE_URL=https://hub.docker.com/r/icmdb/mysql
      - MYSQL_ROOT_PASSWORD=my-root-password
      - MYSQL_USER=mysqld-exporter
      - MYSQL_PASSWORD=mysqld-exporter-password
      - MYSQL_DATABASE=my_database
      - MYSQL_CREATE_DBS=tt1,tt2,tt3
    ports:
      - 3306:3306
    volumes:
     #- ./init/:/docker-entrypoint-initdb.d/:ro
      - ./conf/my.cnf:/root/.my.cnf:ro
      - ./conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./mysqldata/data:/var/lib/mysql:rw
      - ./mysqldata/files:/var/lib/mysql-files:rw
      - ./mysqldata/backup:/backup:rw
    command: ["mysqld", "--max-allowed-packet=512M", "--character-set-server=utf8", "--collation-server=utf8_unicode_ci", "--innodb_buffer_pool_size=1G"]
    restart: always

  mysqld-exporter:
    container_name: mysqld-exporter
    hostname: mysqld-exporter
    image: prom/mysqld-exporter
    ports:
        - 9104:9104
    environment:
      - MYSQLD_EXPORTER_GITHUB=https://github.com/prometheus/mysqld_exporter
      - MYSQLD_EXPORTER_IMAGE_URL=https://hub.docker.com/r/prom/mysqld-exporter
      - 'DATA_SOURCE_NAME=mysqld-exporter:mysqld-exporter-password@(mysql:3306)/performance_schema'
    links:
      - mysql:mysql
    restart: always

  mysqladmin:
    container_name: phpmyadmin
    hostname: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=10
     - PMA_HOST=pma.icmdb.vip
     - PMA_VERBOSE=mysql
     - PMA_PORT=3306
     - MYSQL_ROOT_PASSWORD=my-root-password
     - MYSQL_USER=phpmyadmin
     - MYSQL_PASSWORD=phpmyadmin-password
    #volumes:
    # - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    ports:
     - 8080:80
    links:
     - mysql:mysql
     - mysql:pma.icmdb.vip
    restart: always
