# @reference:
#   https://docs.docker.com/install/linux/docker-ce/ubuntu/
#   https://docs.docker.com/compose/install/
#   https://docs.docker.com/compose/compose-file/
#   https://hub.docker.com/r/phpmyadmin/phpmyadmin
# 
#   chmod 755 ./conf
#   chmod 644 ./conf/mysqld.cnf
#
version: "3"
networks:
  mysqlnet:

services:
  mysql:
    build:
      context: ./
      dockerfile: ./Dockerfile
    networks:
     - mysqlnet
    container_name: mysql
    hostname: mysql
    image: icmdb/mysql:latest
    environment:
      - MYSQL_IMAGE_URL=https://hub.docker.com/r/icmdb/mysql
      - MYSQL_ROOT_PASSWORD=Passw0rd4MySQLRoot
      - MYSQL_USER=mysqld-exporter
      - MYSQL_PASSWORD=Passw0rd4MySQLdExporter
      - MYSQL_DATABASE=icmdb
      - MYSQL_CREATE_DBS=db1,db2,db3
      - MYSQL_CREATE_USERS=user1:pass1:db1,user2:pass2:db2,user3:pass3:db3
    ports:
      - 3306:3306
    volumes:
     #- ./init/:/docker-entrypoint-initdb.d/:ro
      - ./conf/my.cnf:/root/.my.cnf:ro
      - ./conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./mysqldata/data:/var/lib/mysql:rw
      - ./mysqldata/files:/var/lib/mysql-files:rw
      - ./mysqldata/logs:/var/log/mysql:rw
      - ./mysqldata/backup:/backup:rw
    command: ["mysqld", "--max-allowed-packet=512M", "--character-set-server=utf8", "--collation-server=utf8_unicode_ci", "--innodb_buffer_pool_size=1G"]
    restart: always

  mysql-exporter:
    networks:
     - mysqlnet
    container_name: mysql-exporter
    hostname: mysql-exporter
    image: prom/mysqld-exporter
    expose:
     - 9104
    ports:
     - 9104:9104
    environment:
      - MYSQLD_EXPORTER_GITHUB=https://github.com/prometheus/mysqld_exporter
      - MYSQLD_EXPORTER_IMAGE_URL=https://hub.docker.com/r/prom/mysqld-exporter
      - 'DATA_SOURCE_NAME=mysqld-exporter:Passw0rd4MySQLdExporter@(mysql:3306)/performance_schema'
    links:
      - mysql:mysql
    command: ["--collect.engine_innodb_status", "--collect.info_schema.innodb_metrics", "--collect.info_schema.processlist"]
    restart: always

  mysql-admin:
    networks:
     - mysqlnet
    container_name: mysql-admin
    hostname: mysql-admin
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_ARBITRARY=10
     - PMA_HOST=pma.icmdb.vip
     - PMA_VERBOSE=mysql
     - PMA_PORT=3306
     - MYSQL_ROOT_PASSWORD=my-root-password
     - MYSQL_USER=phpmyadmin
     - MYSQL_PASSWORD=phpmyadmin-password
    #volumes:
    # - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    ports:
     - 8080:80
    links:
     - mysql:mysql
     - mysql:pma.icmdb.vip
    restart: always

  mysql-prometheus:
    networks:
     - mysqlnet
    container_name: mysql-prometheus
    hostname: mysql-prometheus
    image: prom/prometheus
    environment:
     - PROM_ENV=
    volumes:
     - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
     - ./prometheus/data/:/prometheus
    command:
     - '--config.file=/etc/prometheus/prometheus.yml'
     - '--storage.tsdb.path=/prometheus'
     - '--storage.tsdb.retention=30d'
     - '--web.console.libraries=/usr/share/prometheus/console_libraries'
     - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
     - 9090:9090
    links:
     - mysql-exporter:mysql-exporter
    restart: always

  mysql-grafana:
    networks:
     - mysqlnet
    container_name: mysql-grafana
    hostname: mysql-grafana
    image: grafana/grafana
    environment:
     - GF_SERVER_ROOT_URL=http://loc.icmdb.vip:3000
     - GF_SECURITY_ADMIN_PASSWORD=Passw0rd4Grafana
     - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
     - GF_PATHS_DATA=/var/lib/grafana
     - GF_PATHS_HOME=/usr/share/grafana
     - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
     - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
     - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
#     - GF_AWS_PROFILES=default
#     - GF_AWS_default_ACCESS_KEY_ID=YOUR_ACCESS_KEY
#     - GF_AWS_default_SECRET_ACCESS_KEY=YOUR_SECRET_KEY
#     - GF_AWS_default_REGION=us-east-1
    volumes:
     - ./grafana/data:/var/lib/grafana
     - ./grafana/plugin:/var/lib/grafana/plugins
    ports:
     - 3000:3000
    links:
     - mysql-prometheus:mysql-prometheus
    restart: always
